name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [ '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --frozen-lockfile --ignore-engines
        env:
          CI: true
      - run: yarn test
